// Generated by CoffeeScript 1.7.1
(function() {
  var WebSocket, cacheBuster, getElementByAttributeValue, onMessage, _ref;

  WebSocket = (_ref = window.WebSocket) != null ? _ref : window.MozWebSocket;

  if (!WebSocket) {
    return;
  }

  window.onload = function() {
    var connection, host, port;
    host = window.location.hostname;
    port = 9485;
    connection = new WebSocket("ws://" + host + ":" + port);
    return connection.onmessage = onMessage;
  };

  onMessage = function(e) {
    var i, message, tags, url, _i, _j, _ref1, _ref2, _results, _results1;
    message = JSON.parse(e.data);
    if (message.reload === 'soft') {
      switch (message.type) {
        case 'css':
          tags = document.getElementsByTagName('link');
          _results = [];
          for (i = _i = 0, _ref1 = tags.length; 0 <= _ref1 ? _i < _ref1 : _i > _ref1; i = 0 <= _ref1 ? ++_i : --_i) {
            if (tags[i].getAttribute('rel') === 'stylesheet') {
              url = tags[i].getAttribute('href');
              url = url.replace(/\?.*$/, '');
              if (message.path.match(url)) {
                _results.push(tags[i].setAttribute('href', cacheBuster(url)));
              } else {
                _results.push(void 0);
              }
            } else {
              _results.push(void 0);
            }
          }
          return _results;
          break;
        case 'image':
          tags = document.getElementsByTagName('img');
          _results1 = [];
          for (i = _j = 0, _ref2 = tags.length; 0 <= _ref2 ? _j < _ref2 : _j > _ref2; i = 0 <= _ref2 ? ++_j : --_j) {
            url = tags[i].getAttribute('src');
            url = url.replace(/\?.*$/, '');
            if (message.path.match(url)) {
              _results1.push(tags[i].setAttribute('src', cacheBuster(url)));
            } else {
              _results1.push(void 0);
            }
          }
          return _results1;
      }
    } else {
      return window.location.reload();
    }
  };

  cacheBuster = function(url) {
    var date;
    date = Math.round(Date.now() / 1000).toString();
    return url + (url.indexOf('?') >= 0 ? '&' : '?') + 'cacheBuster=' + date;
  };

  getElementByAttributeValue = function(attribute, value) {
    var element, _i, _len, _ref1;
    _ref1 = document.getElementsByTagName('*');
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      element = _ref1[_i];
      if (element.getAttribute(attribute) === value) {
        return element;
      }
    }
  };

}).call(this);
